//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GEditPro.rc
//
#define IDR_MANIFEST                    1
#define ID_DEFAULTS                     4
#define ID_DEFAULT                      8
#define IDC_BROWSE                      12
#define ID_DEFAULT_CONE                 16
#define IDD_ABOUTBOX_OLD                20
#define IDC_TEXT_BUILDINFO              24
#define IDB_SPLASH                      28
#define CG_ID_VIEW_DIALOGBAR            32
#define ID_TOOLBAR_COMBOBOX             36
#define IDC_ARROWENTITY                 40
#define ID_INDICATOR_PROGRESS           44
#define ID_INDICATOR_SLOCK              48
#define ID_INDICATOR_SELINFO            52
#define IDD_COMMANDDIALOG               56
#define ID_INDICATOR_WORLDPOS           60
#define ID_INDICATOR_CURSORINFO         64
#define ID_INDICATOR_GRID               68
#define ID_INDICATOR_SNAP               72
#define IDD_COMMANDPANEL                76
#define IDC_PREFABCOMBO                 80
#define IDW_CHILD_STATUS_BAR            84
#define ID_INDICATOR_POSITION           88
#define ID_INDICATOR_SPACE              92
#define ID_INDICATOR_DIMENSION          96
#define IDC_GROUPBAR_COMBO              100
#define IDC_COMBO_PROP1                 104
#define IDC_PROP_COMBO                  108
#define IDC_PROP_EDIT                   112
#define IDC_PROP_BUTTON                 116
#define IDC_PROP_SPIN                   120
#define IDC_PROP_CHECKBOX               124
#define IDC_PROP_COLORBTN               128
#define IDC_PROP_GROUPBTN               132
#define IDC_PROP_RADIOBTN               136
#define IDR_MAINFRAME                   140
#define IDS_CUBE                        141
#define IDS_SPHERE                      142
#define IDS_CONE                        143
#define IDC_PROP_STATIC                 144
#define IDS_STAIRS                      144
#define IDS_ARCH                        145
#define IDS_CYLINDER                    146
#define IDR_THREDTYPE                   148
#define IDR_GEDITPROTYPE                152
#define IDC_PROP_VEC3DBTN               156
#define IDR_BRUSHTOOLS                  160
#define IDS_LOAD_WARNING                164
#define ID_TOOLS_BRUSH_MOVEBRUSH        168
#define IDS_NEWGROUP                    172
#define ID_TOOLS_BRUSH_ROTATEBRUSH      176
#define IDD_BRUSHDIALOG                 180
#define IDS_CREATEGROUPFAILED           184
#define IDD_CREATEBOX                   188
#define IDS_DEFAULTGROUPNAME            192
#define IDW_PREVIEW_WINDOW              196
#define IDB_HOLLOWBOX                   200
#define IDS_NOBLANKMODEL                204
#define IDB_SOLIDBOX                    208
#define IDS_MODELEXISTS                 212
#define IDD_CREATE_SPHEROID             216
#define IDS_CAMERAENTITYNAME            220
#define IDB_SOLIDSPHERE                 224
#define IDS_MAPERROR                    228
#define IDB_HOLLOWSPHERE                232
#define IDD_CREATE_CYL                  236
#define IDB_CYLINDERBIT                 240
#define IDD_GRIDSETTINGSDIALOG          244
#define IDD_BSPMANAGERDIALOG            248
#define IDD_ENTITIES                    252
#define IDD_SELECTCLASSNAME             256
#define IDD_GROUPDIALOG                 260
#define IDD_STAIRCASEDIALOG             264
#define IDR_THRED_PALETTE1              268
#define IDD_GLOBALSETTINGS              272
#define IDD_FACEDIALOG                  276
#define IDD_QUICKVIEWER_DISPLAY         280
#define IDC_BTN_VIEW_REBUILD            284
#define IDD_TABDIALOG                   288
#define IDC_BTN_REBUILD_COMMAND         292
#define IDC_BTN_REBUILD_HIDE            296
#define T_FILE                          300
#define IDR_MODE                        304
#define IDR_OBJECTS                     308
#define IDD_BRUSH_ENTITY_DIALOG         312
#define IDB_LIGHTBULB                   316
#define IDI_CUBE_PRIMITIVE              320
#define IDD_TIP                         324
#define IDB_SHOWALL                     328
#define IDI_SPHEROID_PRIMITIVE          332
#define IDI_CYLINDER_PRIMITIVE          336
#define IDB_SHOWVISIBLEGROUPS           340
#define IDI_STAIRCASE_PRIMITIVE         344
#define IDB_SHOWCURRENTGROUP            348
#define IDI_LIGHT_ENTITY                352
#define IDI_PLAYERSTART_ENTITY          356
#define IDB_HANDLECORNER                360
#define IDB_HANDLEEDGE                  364
#define IDB_ROTATEHANDLETL              368
#define IDB_ROTATEHANDLETR              372
#define CG_IDS_TIPOFTHEDAY              376
#define IDB_ROTATEHANDLEBL              380
#define IDB_ROTATEHANDLEBR              384
#define IDI_ACTOR_ENTITY                388
#define IDI_FLIPVERTICAL                392
#define IDB_SHEARHANDLELR               396
#define IDI_FLIPHORIZONTAL              400
#define IDD_CREATE_ARCH                 404
#define IDI_ARCH_PRIMITIVE              408
#define IDB_SHEARHANDLETB               412
#define IDD_PROGRESSDIALOG              416
#define IDD_CREATE_CONE                 420
#define IDI_CONE_PRIMITIVE              424
#define IDD_COMPILEDIALOG               428
#define CG_IDS_TIPOFTHEDAYMENU          432
#define CG_IDS_DIDYOUKNOW               436
#define CG_IDS_FILE_ABSENT              440
#define CG_IDP_FILE_CORRUPT             444
#define CG_IDS_TIPOFTHEDAYHELP          448
#define ID_MAINFRAME_TIMER              452
#define IDC_PANCURSOR                   456
#define IDT_TIMER_CHILDFRAME            460
#define IDC_ARROWBRUSH                  464
#define IDC_POINTER                     468
#define IDD_CONSOLE                     472
#define IDD_OBJ_NAME_DLG                480
#define IDI_LIBOBJECT                   484
#define IDD_DIALOG1                     488
#define IDD_PROPEDIT                    492
#define IDB_VERTEX                      496
#define IDB_SELVERTEX                   500
#define IDD_KEYEDIT                     504
#define IDB_TERRAIN                     508
#define IDD_POINTKEYEDIT                512
#define IDD_STRUCTEDIT                  516
#define IDD_MODELEDIT                   520
#define IDD_MODELKEY                    524
#define IDI_PLAY                        528
#define IDI_RRSTART                     532
#define IDI_RRFRAME                     536
#define IDI_STOP                        540
#define IDI_FFFRAME                     544
#define IDI_FFEND                       548
#define IDD_ENTITYVISIBILITY            552
#define IDR_GROUPBAR                    556
#define ID_BRUSH_GROUPS_ADDTOGROUP      560
#define IDB_TEXVIEW                     564
#define IDD_GROUPBAR                    568
#define IDD_PREFERENCES                 572
#define IDD_SKYDIALOG                   576
#define IDD_EVENTEDIT                   580
#define IDD_PATHSDIALOG                 584
#define IDD_PROJECTOPTIONS              588
#define IDC_EYEDROPPER                  592
#define IDD_LEVELOPTIONS                596
#define IDC_CAMERA                      600
#define IDD_BOOLEDIT                    604
#define IDD_DIALOG2                     608
#define IDD_PRINT_VIEW_DLG              612
#define IDC_CURSOR1                     616
#define IDC_CYLINDER                    620
#define IDC_SPHERE                      624
#define IDC_SHEET                       628
#define IDC_VERTEX                      632
#define IDC_LIGHT                       636
#define IDC_CURSOR_PLUS                 640
#define IDC_DRAGCOPY                    644
#define IDC_DRAGMOVE                    648
#define IDC_MOVESELECT                  652
#define IDC_ROTATE                      656
#define IDD_ERROR                       660
#define IDC_ROTATIONCENTER              664
#define IDC_SHEARLR                     668
#define IDC_SHEARTB                     672
#define IDC_CUBE                        676
#define IDD_ABOUTBOX                    680
#define IDD_OBJECTSDLG                  684
#define IDD_TEXTURE_DLG                 688
#define IDR_TEXT1                       692
#define IDR_TEMPLATES                   696
#define IDD_TEMPLATES_DLG               700
#define IDI_CUBE_ICON                   704
#define IDI_SPHERE_ICON                 708
#define IDI_CYLINDER_ICON               712
#define IDI_ARCH_ICON                   716
#define IDI_STAIRS_ICON                 720
#define IDI_CONE_ICON                   724
#define IDD_PROPERTIES_DLG              728
#define IDD_CONSOLE_DIALOG              732
#define IDD_PROPERTIES_GENERIC_DLG      736
#define IDR_POPUP_MENU                  740
#define IDB_ARCH                        744
#define IDB_CONE                        748
#define IDB_STAIRS                      752
#define IDB_LOGO                        756
#define IDB_ENTITY                      760
#define IDB_G3D_SPLASH                  764
#define IDB_PROTOGAME                   768
#define IDD_PLUGIN1_DIALOG              772
#define IDR_PLUGINTEXT                  776
#define IDI_ICON1                       780
#define IDC_RAN_ARROW                   784
#define IDD_TEXTUREDLG_TEXLIST          788
#define IDD_GENEDIT_PREVIEW             792
#define IDI_SKY_ICON                    796
#define IDB_SKYBITMAP                   800
#define IDR_VIEW_TOOLBAR                804
#define IDD_VIEWMGR_DLG                 808
#define IDM_PROPERTIES_PANEL            816
#define IDC_RESET_ALL                   820
#define IDC_BULB                        824
#define IDC_EDIT1                       828
#define IDC_STARTUP                     832
#define IDC_EDIT10                      836
#define IDC_CONE_HEIGHT                 840
#define IDC_NEXTTIP                     844
#define IDC_EDIT11                      848
#define IDC_CONE_STRIPS                 852
#define IDC_EDIT12                      856
#define IDC_COMMAND_TAB                 860
#define IDC_CONE_WALL                   864
#define IDC_TIPSTRING                   868
#define IDC_BOUNCELIMIT                 872
#define IDC_FACELIGHTINTENSITY          876
#define GROUP_LOCK                      880
#define IDC_LIGHTSCALE                  884
#define IDC_PATCHSIZE                   888
#define IDC_REFLECTSCALE                892
#define IDC_MINLIGHT                    896
#define IDC_RESET_POSITION              900
#define IDC_RESET_ROTATION              904
#define IDC_RESET_SCALE                 908
#define IDC_SOLID                       912
#define IDC_XShear                      916
#define IDC_HOLLOW                      920
#define IDC_YSHEAR                      924
#define IDC_XSIZE                       928
#define IDC_ZSHEAR                      932
#define IDC_RING                        936
#define IDC_YSIZE                       940
#define IDC_RESET_SHEAR                 944
#define IDC_ZSIZE                       948
#define IDC_THICKNESS                   952
#define IDC_PICTURE                     956
#define IDC_VERTSTRIPES                 960
#define IDC_YSIZE2                      964
#define IDC_HORSTRIPES                  968
#define IDC_XSIZE2                      972
#define IDC_RINGLENGTH                  976
#define IDC_XSIZEBOT                    980
#define IDC_ZSIZEBOT                    984
#define IDC_TOPXSIZE                    988
#define GRUP_CB_CURRENT                 992
#define IDC_TOPXOFF                     996
#define IDC_TOPZOFF                     1000
#define IDC_BOTXSIZE                    1004
#define IDC_BOTZSIZE                    1008
#define IDC_BOTXOFF                     1012
#define IDC_BOTZOFF                     1016
#define IDC_TOPZSIZE                    1020
#define IDC_GRIDSIZE                    1024
#define IDC_RebuildQuick                1028
#define IDC_REBUILDOPTIMAL              1032
#define IDC_ORIGINAL_POLYS              1036
#define IDC_SPLITS                      1040
#define IDC_TOTAL_POLYS                 1044
#define IDC_NODES                       1048
#define IDC_COPLANAR_NODES              1052
#define IDC_Defaults                    1056
#define IDC_PROGRESS1                   1060
#define IDC_PAIRS                       1064
#define IDC_PROPERTIESLIST              1068
#define IDC_SHOWLIGHTS                  1072
#define IDC_NEWKEYVALUE                 1076
#define IDC_KEY_EDIT                    1080
#define IDC_VALUE_EDIT                  1084
#define IDC_ENTITYLIST                  1088
#define IDC_ASSOCIATE_SELECTEDBRUSH     1092
#define IDC_ASSOCIATEGROUP              1096
#define IDC_NEWENTITY                   1100
#define IDC_NEWLIGHT                    1104
#define IDC_DELETEKEYVALUE              1108
#define IDC_DELETEENTITY                1112
#define IDC_LIST1                       1116
#define IDC_COLOURBUTTON                1120
#define IDC_CHECK1                      1124
#define IDC_MAKE_RAMP                   1128
#define IDC_BRUSHLIST                   1132
#define IDC_SKYRIGHT                    1136
#define IDC_VISDETAIL                   1140
#define IDC_NAME                        1144
#define IDC_CHECK3                      1148
#define IDC_SKYTOP                      1152
#define IDC_HULLSIZE                    1156
#define IDC_CHECK4                      1160
#define IDC_SKYBOTTOM                   1164
#define IDC_SKYFRONT                    1168
#define IDC_XSIZETOP                    1172
#define IDC_SKYBACK                     1176
#define IDC_ZSIZETOP                    1180
#define IDC_HEIGHT                      1184
#define IDC_WIDTH                       1188
#define IDC_LENGTH                      1192
#define IDC_NUMSLITS                    1196
#define IDC_NUMBEROFSTAIRS              1200
#define IDC_RADIUS                      1204
#define IDC_BUILDWATER                  1208
#define IDC_WALLSIZE                    1212
#define IDC_SIZE16                      1216
#define IDC_SIZE32                      1220
#define IDC_SIZE64                      1224
#define IDC_SIZE8                       1228
#define IDC_SHOWCOARSE                  1232
#define IDC_USEROTSNAP                  1236
#define IDC_SNAP15                      1240
#define IDC_SNAP30                      1244
#define IDC_SNAP45                      1248
#define IDC_SNAP60                      1252
#define IDC_SHOWFINE                    1256
#define IDC_SNAP90                      1260
#define IDC_ROTSNAPDEGREES              1264
#define IDC_BROWSEPAL                   1268
#define IDC_SIZE4                       1272
#define IDC_BROWSEWAD                   1276
#define IDC_PALETTEPATH                 1280
#define IDC_WADPATH                     1284
#define IDC_DISASSOCIATE                1288
#define IDC_AVENGERPATH                 1292
#define IDC_BROWSEAVENGER               1296
#define IDC_SBXOFFSET_UNIT              1300
#define IDC_SBYOFFSET_UNIT              1304
#define IDC_SBXSCALE_UNIT               1308
#define IDC_SBYSCALE_UNIT               1312
#define IDC_SBANGLE_UNIT                1316
#define IDC_SBXOFFSET_INCR              1320
#define IDC_CBSKYBACK                   1324
#define IDC_SBYOFFSET_INCR              1328
#define IDC_CBSKYLEFT                   1332
#define IDC_SBXSCALE_INCR               1336
#define IDC_SBYSCALE_INCR               1340
#define IDC_SBANGLE_INCR                1344
#define IDC_APPLY                       1348
#define IDC_RESTORE                     1352
#define IDC_COLOR                       1356
#define IDC_CANCEL                      1360
#define LIST_TV_ITEMS                   1364
#define IDD_DISCLAIMER                  1368
#define IDD_GROUPS                      1372
#define IDD_LISTS                       1376
#define IDC_GROUP1                      1380
#define IDD_MODELS                      1384
#define IDC_TEXTURELIST                 1388
#define IDD_TEXTUREDIALOG               1392
#define IDC_TEXTUREIMAGE                1396
#define IDD_PROPERTYPANEL               1400
#define IDD_PROPERTIES_PANEL            1404
#define IDC_APPLYTEXTURE                1408
#define IDC_CUBE_PRIMITIVE              1412
#define IDC_SPHEROID_PRIMITIVE          1416
#define IDC_CYLINDER_PRIMITIVE          1420
#define IDC_STAIRCASE_PRIMITIVE         1424
#define IDC_LIGHT_ENTITY                1428
#define IDC_BUILDALWAYS                 1432
#define IDC_ENTITIES                    1436
#define IDC_PLAYERSTART_ENTITY          1440
#define IDC_FLIPVERTICAL                1444
#define IDC_ACTOR_ENTITY                1448
#define IDC_FLIPHORIZONTAL              1452
#define IDC_ARCH_PRIMITIVE              1456
#define IDC_CONE_PRIMITIVE              1460
#define IDC_STARTANGLE                  1464
#define IDC_ENDANGLE                    1468
#define IDC_STATUSPROGRESS1             1472
#define IDC_STATUSPROGRESS2             1476
#define IDC_FUNNEL                      1480
#define IDC_ADDGROUP                    1484
#define IDC_VISNONE                     1488
#define IDC_VISLEVEL1                   1492
#define IDC_VISLEVEL2                   1496
#define IDC_VISLEVEL3                   1500
#define IDC_VISLEVEL4                   1504
#define IDC_RUNGBSP                     1508
#define IDC_RUNLIGHT                    1512
#define IDC_RunAvenger                  1516
#define IDC_VISLEVEL0                   1520
#define IDC_VIS                         1524
#define IDC_TCUT                        1528
#define IDC_CONEDIT                     1532
#define IDC_TSHEET                      1536
#define IDC_STATIC2                     1540
#define IDC_MILLIRADIO                  1544
#define IDC_BRUSHEMPTY                  1548
#define IDC_CENTIRADIO                  1552
#define IDC_METERRADIO                  1556
#define IDC_RADBOOL                     1560
#define IDC_8RADIO                      1564
#define IDC_EXSAMPBOOL                  1568
#define IDC_RADIO5                      1572
#define IDC_16RADIO                     1576
#define IDC_RADIO_NOCOLLIDE             1580
#define IDC_FASTPBOOL                   1584
#define IDC_RADIO6                      1588
#define IDC_32RADIO                     1592
#define IDC_BRUSHHOLLOW                 1596
#define IDC_DIRECT3D_RADIO              1600
#define IDC_FULLVIS                     1604
#define IDC_1RADIO                      1608
#define IDC_VISVERBOSE                  1612
#define IDC_2RADIO                      1616
#define IDC_BSPVERBOSE                  1620
#define IDC_ENTITYCOMBO                 1624
#define IDC_4RADIO                      1628
#define IDC_ENTITYVERBOSE               1632
#define IDC_USEMINLIGHT                 1636
#define IDC_TJUNCT                      1640
#define IDC_XEDIT                       1644
#define IDC_YEDIT                       1648
#define IDC_ZEDIT                       1652
#define IDC_STRUCTLIST                  1656
#define IDC_SIZETEXT                    1660
#define IDC_MODELLIST                   1664
#define IDC_BRUSHLOCK                   1668
#define IDC_DESELECTBRUSHES             1672
#define IDC_SELECTBRUSHES               1676
#define IDC_SELECTBRUSHES2              1680
#define IDC_SELECTBRUSHES3              1684
#define IDC_ADDTOCURRENT                1688
#define IDC_SELECTBRUSHES4              1692
#define IDC_REMOVEFROMCURRENT           1696
#define IDC_VISIBLE                     1700
#define IDC_SUPPRESSHIDDEN              1704
#define IDC_SELECTBRUSHES5              1708
#define IDC_CREATENEWGROUP              1712
#define IDC_REMOVEGROUP                 1716
#define IDC_DESELECT                    1720
#define IDC_ADDKEY                      1724
#define IDC_ANIMATE                     1728
#define IDC_ADDEVENT                    1732
#define IDC_DELETEKEY                   1736
#define IDC_SELECT                      1740
#define IDC_DELETEEVENT                 1744
#define IDC_DELETEMODEL                 1748
#define IDC_MODELCOMBO                  1752
#define IDC_KEYSLIST                    1756
#define IDC_ADDMODEL                    1760
#define IDC_ADDBRUSHES                  1764
#define IDC_REMOVEBRUSHES               1768
#define IDC_EDITMODEL                   1772
#define IDC_EDITKEY                     1776
#define IDC_EDITEVENT                   1780
#define IDC_TEXELRADIO                  1784
#define IDC_METRICRADIO                 1788
#define IDC_GROUPCOMBO                  1792
#define IDC_METRICGRID                  1796
#define IDC_LOCKED                      1800
#define IDC_TEXELGRID                   1804
#define IDC_SPINROTSNAPDEGREES          1808
#define IDC_BRUSHSOLID                  1812
#define IDC_SETMODELORIGIN              1816
#define IDC_BRUSHWINDOW                 1820
#define IDC_CLONEMODEL                  1824
#define IDC_BRUSHWAVY                   1828
#define IDC_LOCKORIGIN                  1832
#define IDC_BRUSHFLOCKING               1836
#define IDC_TUTORIAL                    1840
#define IDC_BRUSHCLIP                   1844
#define IDC_BRUSHHINT                   1848
#define IDC_TUTORIAL2                   1852
#define IDC_FACEMIRROR                  1856
#define IDC_BRUSHSHEET                  1860
#define IDC_BRUSHAREA                   1864
#define IDC_FACEFULLBRIGHT              1868
#define IDC_PREFSGRIDBG                 1872
#define IDC_FACEGOURAUD                 1876
#define IDC_DEMO                        1880
#define IDC_FACESKY                     1884
#define IDC_PREFSGRIDMAJOR              1888
#define IDC_PREFSGRID                   1892
#define IDC_FACEFLAT                    1896
#define IDC_DEMO2                       1900
#define IDC_BRUSHSUBTRACT               1904
#define IDC_SKYLEFT                     1908
#define IDC_FACELIGHT                   1912
#define IDC_PREFSGRIDMINOR              1916
#define IDC_PREFSSNAPGRID               1920
#define IDC_CBSKYRIGHT                  1924
#define IDC_PATHPREFS                   1928
#define IDC_BRUSHTRANSLUCENT            1932
#define IDC_CBSKYTOP                    1936
#define IDC_CBSKYBOTTOM                 1940
#define IDC_CBSKYFRONT                  1944
#define IDC_BRUSHDETAIL                 1948
#define IDC_EVENTTIME                   1952
#define IDC_EVENTSTRING                 1956
#define IDC_ENTITIESONLY                1960
#define IDC_EDITXOFFSET                 1964
#define IDC_ERROR                       1968
#define IDC_EDITYOFFSET                 1972
#define IDC_EDITXSCALE                  1976
#define IDC_EDITYSCALE                  1980
#define IDC_EDITANGLE                   1984
#define IDC_MORE                        1988
#define IDC_CBXOFFSET                   1992
#define IDC_LOG                         1996
#define IDC_CBYOFFSET                   2000
#define IDC_CBXSCALE                    2004
#define IDC_WARNINGICON                 2008
#define IDC_CBYSCALE                    2012
#define IDC_CBANGLE                     2016
#define IDC_EDITXLIGHTSCALE             2020
#define IDC_EDITYLIGHTSCALE             2024
#define IDC_SBXLIGHTSCALE_UNIT          2028
#define IDC_SBYLIGHTSCALE_UNIT          2032
#define IDC_SBXLIGHTSCALE_INCR          2036
#define IDC_SBYLIGHTSCALE_INCR          2040
#define IDC_CBXLIGHTSCALE               2044
#define IDC_CBYLIGHTSCALE               2048
#define IDC_EDITTRANSLUCENCY            2052
#define IDC_LBLTRANSLUCENCYVALUE        2056
#define IDC_LBLHULLSIZE                 2060
#define IDC_EDITTXLSEARCH               2064
#define IDC_EDITPREVIEW                 2068
#define IDC_EDITHEADERS                 2072
#define IDC_EDITOBJECTSDIR              2076
#define IDC_EDITTXLIB                   2080
#define IDC_PATHS                       2084
#define IDC_COMPILEOPTIONS              2088
#define IDC_SAVE                        2092
#define IDC_LIGHTMAPSCALE               2096
#define IDC_DRAWSCALE                   2100
#define IDC_BOOLLIST                    2104
#define IDC_EDITTXL                     2108
#define IDC_CONTENTSLIST                2112
#define IDC_EDITHEADERSDIR              2116
#define IDC_MIPMAPBIAS                  2120
#define IDC_TEXTURELOCK                 2124
#define IDC_AXISX                       2128
#define IDC_REFLECTIVITY                2132
#define IDC_AXISY                       2136
#define IDC_FACETRANSLUCENCY            2140
#define IDC_AXISZ                       2144
#define IDC_EDITSPEED                   2148
#define IDC_EDITSCALE                   2152
#define IDC_TRANSPARENT                 2156
#define IDC_BROWSETXL                   2160
#define IDC_BUTTON1                     2164
#define IDC_OBJACTOR_BTN                2168
#define IDC_TEMPLATE_APPLY              2172
#define IDC_FACE_APPLYBTN               2176
#define IDC_CONSOLE_COPY_BTN            2180
#define IDC_PLUGIN1_BRSBTN              2184
#define IDC_LISTBUDDY                   2188
#define IDC_TEST_BUTTON                 2192
#define IDC_CLEAR_ALL_BTN               2196
#define IDC_SHOW_PREVIEW_BTN            2200
#define IDC_BRUSH_ALL_SAME              2204
#define IDC_BTN_VIEW_UL                 2208
#define IDC_BUTTON2                     2212
#define IDC_OBJVISUAL_BTN               2216
#define IDC_PLUGIN1_PLAYBTN             2220
#define IDC_CONSOLE_QUICKVIEW_BTN       2224
#define IDC_ZERO_CAMERA_BTN             2228
#define IDC_BTN_VIEW_UR                 2232
#define IDC_BUTTON3                     2236
#define IDC_OBJSOUND_BTN                2240
#define IDC_CLOSE_CONSOLEBTN            2244
#define IDC_PLUGIN_STOPBTN              2248
#define IDC_PREVIEW_BROWSE_BTN          2252
#define IDC_BTN_VIEW_LL                 2256
#define IDC_BUTTON4                     2260
#define IDC_OBJOTHER_BTN                2264
#define IDC_TEXTURE_LIST                2268
#define IDC_OBJECTLIST_ACT              2272
#define IDC_TEXTURE_BMP                 2276
#define IDC_OBJECTLIST_ACT3             2280
#define IDC_TEXTURE_BTN                 2284
#define IDC_OBJECTLIST_ACT4             2288
#define IDC_SIZE_TXT                    2292
#define IDC_OBJECTLIST_ACT5             2296
#define LIST_GROUP_ITEMS                2300
#define IDC_BUTTON_CUBE                 2304
#define IDC_BUTTON_SPHERE               2308
#define IDC_BUTTON_ARCH                 2312
#define IDC_BUTTON_CYLINDER             2316
#define IDC_PREFAB_LIST                 2320
#define IDC_BUTTON_STAIRS               2324
#define IDC_BUTTON_CONE                 2328
#define IDC_CURRENT_PREFAB              2332
#define IDC_CURRENT_ITEM                2332
#define IDC_PREFAB_BTN                  2336
#define IDC_PROPERTIESTAB               2340
#define IDC_CONSOLE_EDIT                2344
#define IDC_COMBO1                      2348
#define IDC_CBALLSAME                   2352
#define IDC_RADIO1                      2356
#define IDC_RADIO_640                   2360
#define IDC_RADIO2                      2364
#define IDC_RADIO_800                   2368
#define IDC_RADIO3                      2372
#define IDC_RADIO_1024                  2376
#define IDC_LIST2                       2380
#define IDC_PLUGIN1_WAV1                2384
#define IDC_PREVIEW_LIST                2388
#define IDC_ENTITY_BTN                  2392
#define IDC_SKYBUTTON                   2396
#define IDC_OBJACTOR_LIST               2400
#define IDC_OBJVISUAL_LIST              2404
#define IDC_OBJSOUND_LIST               2408
#define IDC_OBJOTHER_LIST               2412
#define IDC_ENTITIES_STATIC             2416
#define ID_APPLY_BOX_BTN                2420
#define IDC_CUSTOM_TEMPLATE_BTN         2424
#define IDC_ADD_ARCH_BTN                2428
#define IDC_CUSTOM_ARCH_BTN             2432
#define IDC_ADD_CONE_BTN                2436
#define IDC_CUSTOMIZE_CONE_BTN          2440
#define IDC_CONE_WIDTH                  2444
#define IDC_SOLID_CONE                  2448
#define IDC_HOLLOW_CONE                 2452
#define IDC_TCUT_CONE                   2456
#define IDC_CUSTOMIZE_CYL_BTN           2460
#define IDC_APPLY_CYL_BTN               2464
#define IDC_CUSTOMIZE_SPHERE_BTN        2468
#define IDC_ADD_SPHERE_BTN              2472
#define IDC_CUSTOMIZE_STAIRS            2476
#define IDC_ADD_STAIRS                  2480
#define IDC_BUTTON5                     2484
#define IDC_BUTTON7                     2488
#define IDC_PATH_LIST                   2492
#define IDC_TEXTURE_IMAGE_LIST          2496
#define IDC_MYDRAW                      2500
#define IDC_TEXTURE_LISTBOX             2504
#define IDC_TXT_TEXTURENAME             2508
#define IDC_ALL_THE_SAME                2512
#define IDC_ALL_SAMEBTN                 2516
#define IDC_NULLCOMBO                   2520
#define IDC_PREVIEWFRAME                2524
#define IDC_RADIO_COLLIDE               2528
#define IDC_CURRENT_SAVE_PATH           2532
#define IDC_TRILOBITE_WORKS             2536
#define IDC_SOFTWARE_RADIO              2540
#define IDC_GLIDE_RADIO                 2544
#define IDC_SOFTWARE_TEXT               2548
#define IDC_CAMERA_Y                    2552
#define IDC_CAMERA_Z                    2556
#define IDC_CAMERA_X                    2560
#define IDC_CAMERA_SLIDERX              2564
#define IDC_CAMERA_SLIDERY              2568
#define IDC_CAMERA_SLIDERZ              2572
#define IDC_SCALE_WORLD                 2576
#define IDC_CURRENT_SCALE               2580
#define IDC_ENTITY_DRAW_SCALE           2584
#define IDC_TEXEL1_RADIO                2588
#define IDC_TEXEL2_RADIO                2592
#define IDC_TEXEL4_RADIO                2596
#define IDC_TEXEL8_RADIO                2600
#define IDC_TEXEL16_RADIO               2604
#define IDC_TEXEL32_RADIO               2608
#define IDC_SPIN_ENTITY_VISIBILITY      2612
#define IDC_BTN_VIEW_LR                 2616
#define IDC_BTN_VIEW_RESTORE            2620
#define IDC_EDIT_PREVIEWLEVEL_PATH      2624
#define IDM_TOOLS_PLACECUBE             2628
#define IDM_TOOLS_PLACESPHEROID         2632
#define IDM_TOOLS_PLACECYLINDER         2636
#define IDM_TOOLS_PLACESTAIRCASE        2640
#define IDM_TOOLS_PLACEARCH             2644
#define IDM_TOOLS_PLACELIGHT            2648
#define IDM_TOOLS_PLACEPREFAB           2652
#define IDM_MODE_ADJUST                 2656
#define IDM_MODE_ROTATESHEAR            2660
#define IDM_MODE_VERTEX                 2664
#define IDM_TOOLS_PLACECAMERA           2668
#define IDM_TOOLS_PLACEUSEROBJ          2672
#define IDM_TOOLS_UPDATE_SELECTION      2676
#define IDS_UPDATE_ALL                  2680
#define ID_BRUSH_PRIMITIVES_CUBE        2684
#define ID_BRUSH_PRIMITIVES_PYRAMID     2688
#define ID_BRUSH_PRIMITIVES_SPHEROID    2692
#define ID_BRUSH_PRIMITIVES_CONE        2696
#define ID_BRUSH_PRIMITIVES_CYLINDER    2700
#define ID_BRUSH_SUBTRACTFROMWORLD      2704
#define ID_TOOLS_CAMERA                 2708
#define ID_AXIS_X                       2712
#define ID_AXIS_Y                       2716
#define ID_AXIS_Z                       2720
#define ID_TOOLS_BRUSH_MOVEROTATEBRUSH  2724
#define ID_TOOLS_BRUSH_SCALEBRUSH       2728
#define ID_TOOLS_BRUSH_RESETBRUSH       2732
#define ID_TOOLS_BRUSH_ATTRIBUTES       2736
#define ID_TOOLS_BRUSH_SHOWBRUSH        2740
#define ID_FILE_EXPORT                  2744
#define ID_TOOLS_USEGRID                2748
#define ID_TOOLS_GRIDSETTINGS           2752
#define ID_VIEW_3DWIREFRAME             2756
#define ID_VIEW_SOLIDRENDER             2760
#define ID_VIEW_TOPVIEW                 2764
#define ID_VIEW_SIDEVIEW                2768
#define ID_VIEW_FRONTVIEW               2772
#define ID_VIEW_TEXTUREVIEW             2776
#define ID_VIEW_4VIEWS                  2780
#define ID_TOOLS_BSPMANAGER             2784
#define ID_TOOLS_BRUSH_SHEARBRUSH       2788
#define ID_ENTITIES_PLACELIGHT          2792
#define ID_ENTITIES_EDITOR              2796
#define ID_TOOLS_ENTITY                 2800
#define ID_ENTITIES_SHOW                2804
#define ID_GROUPS_MAKENEWGROUP          2808
#define ID_BRUSH_GROUPEDITOR            2812
#define ID_VIEW_SHOW_ALLGROUPS          2816
#define ID_VIEW_SHOW_VISIBLEGROUPS      2820
#define ID_VIEW_SHOW_CURRENTGROUP       2824
#define ID_TOOLS_BRUSH_ADJUSTMENTMODE   2828
#define ID_BRUSH_SELECTED_DELETE        2832
#define ID_BRUSH_SELECTED_COPYTOCURRENT 2836
#define ID_BRUSH_PRIMITIVES_STAIRCASE   2840
#define ID_TOOLS_BRUSH_ROTATE90         2844
#define ID_VIEW_TEXTUREBROWSER          2848
#define ID_FILE_MAPSETTINGS             2852
#define ID_GBSPNOWATER                  2856
#define ID_ENTITIES_COPYCURRENT         2860
#define ID_ENTITIES_HIDENONLIGHTS       2864
#define ID_TOOLS_BRUSH_MOVESELECTEDBRUSHES 2868
#define ID_TOOLS_GROUPMOVEMENTMODE      2872
#define ID_BRUSH_REMOVESELECTEDFROMGROUP 2876
#define IDM_TOOLS_PREFABCOMBO           2880
#define ID_TOOLS_FACE_ATTRIBUTES        2884
#define ID_TOOLS_FACE_RESETFACE         2888
#define ID_TOOLS_FACE_ADJUSTMENTMODE    2892
#define ID_CONSTRAINHOLLOWS             2896
#define ID_GENERALSELECT                2900
#define IDM_ANIM                        2904
#define ID_VIEW_OLDVIEW                 2908
#define ID_TOOLS_RESET_THING            2912
#define ID_THING_ATTRIBUTES             2916
#define ID_TOOLS_CARVE                  2920
#define IDC_VIEWTOOLBAR_COMBOBOX        2924
#define ID_VIEW_3DVIEWBARS              2928
#define ID_TOOLS_BRUSH_SHOWASSOCIATEDENTITY 2932
#define ID_ENTITY_CENTERINBRUSH         2936
#define ID_CENTERTHING                  2940
#define ID_COMPILE                      2944
#define ID_TOOLS_TEMPLATE               2948
#define ID_MODEL_NEW                    2952
#define ID_NEW_LIB_OBJECT               2956
#define ID_MODEL_DELETE                 2960
#define ID_MODEL_ADDSELECTEDBRUSHES     2964
#define ID_MODEL_REMOVESELECTEDBRUSHES  2968
#define ID_MODEL_SELECTBRUSHES          2972
#define ID_MODEL_DESELECTMODELBRUSHES   2976
#define ID_MODEL_SELECTMODEL            2980
#define ID_ENTITYVISIBILITY             2984
#define ID_VIEW_NEW                     2988
#define ID_BRUSHINFORMATION             2992
#define IDC_PLACE_OBJECT_BUTTON         2996
#define IDS_CANT_OPEN_FILE              3000
#define IDC_OBJECT_SELECT_COMBO         3004
#define IDC_ENTITY_COMBO                3008
#define IDC_ENTITIES_COMBO              3012
#define IDM_MODEBAR                     3016
#define IDM_TABBAR                      3020
#define IDM_GROUPBAR                    3024
#define ID_GROUPBAR_SEP                 3028
#define ID_GROUPBAR_COM                 3032
#define ID_ADDTOCURRENT                 3036
#define ID_REMOVEFROMCURRENT            3040
#define ID_DESELECTALL                  3044
#define ID_SELECTALL                    3048
#define IDM_REBUILD_BSP                 3052
#define ID_VIEWLEAKFINDER               3056
#define IDM_PREFERENCES                 3060
#define ID_VIEW_SHOW_CLIP               3064
#define ID_VIEW_SHOW_HINT               3068
#define ID_VIEW_SHOW_DETAIL             3072
#define ID_TOOLS_SCALEWORLD             3076
#define ID_TOOLS_BRUSH_MAKENEWEST       3080
#define ID_TOOLS_SETTEXTURESCALE        3084
#define ID_EDIT_DELETE                  3088
#define ID_BRUSH_PRIMITIVES_ARCH        3092
#define ID_TOOLS_NEXTBRUSH              3096
#define ID_TOOLS_PREVBRUSH              3100
#define ID_TOOLS_ADDTOLEVEL             3104
#define ID_TOOLS_TOGGLEADJUSTMODE       3108
#define ID_VIEW_ZOOMIN                  3112
#define ID_VIEW_ZOOMOUT                 3116
#define ID_FILE_IMPORT                  3120
#define ID_HELP_HOWDOI                  3124
#define IDM_LEVELOPTIONS                3128
#define IDS_CANTLOADTXL                 3132
#define IDS_ENTITY_WARNING              3136
#define IDM_PROPERTIES_BAR              3140
#define IDM_COMMAND_PANEL               3144
#define IDM_CONSOLE                     3148
#define IDM_POPUP_CAMERA                3152
#define IDM_POPUP_FACEBRUSH             3156
#define IDM_POPUP_TEMPLATE              3160
#define IDM_POPUP_TEXTURE               3164
#define IDM_POPUP_MOVE_ROTATE           3168
#define IDM_POPUP_RESIZE                3172
#define IDM_POPUP_SHEAR                 3176
#define IDM_POPUP_ROTATE                3180
#define IDM_POPUP_CENTER                3184
#define IDM_PLUGIN_1                    3188
#define IDM_BUTTON_LABELS               3192
#define IDM_PREVIEW                     3196
#define ID_BUTTON32992                  3200
#define ID_BUTTON32995                  3204
#define ID_BUTTON32996                  3208
#define ID_BUTTON32997                  3212
#define ID_BUTTON32998                  3216
#define ID_BUTTON32999                  3220
#define ID_VIEW_VIEWMGR                 3224
#define ID_FILE_PRINT_TEDIT_VIEW        3228
#define ID_FILE_PRINT_PREVIEW_T_EDIT_VIEW 3232
#define ID_BUTTON33003                  3236
#define ID_BUTTON33004                  3240
#define IDS_TAB_TEXTURES                3244
#define IDS_TAB_LISTS                   3248
#define IDS_TAB_MODELS                  3252
#define IDS_TAB_GROUP                   3256
#define IDS_TOOLBAR_GENERAL             3260
#define IDS_TOOLBAR_OBJECT              3264
#define IDS_TOOLBAR_MODE                3268
#define IDS_TOOLBAR_GROUP               3272
#define IDS_TOOLBAR_BRUSH               3276
#define IDS_TAB_OBJECTS                 3280
#define IDS_TAB_TEMPLATES               3284
#define IDS_TAB_PROPERTIES              3288
#define IDS_TAB_CONSOLE                 3292
#define IDC_BTN_PRINT_TOP               3296
#define IDC_BTN_PRINT_FRONT             3300
#define IDC_BTN_PRINT_SIDE              3304
#define IDC_BTN_PRINT_TEXTURED          3308
#define ID_EDIT_UNDO4000                4000
#define ID_EDIT_REDO1                   4001
#define ID_EDIT_PASTE4002               4002
#define IDR_WAVE_WOOSH                  4014
#define IDR_WAVE_                       4015
#define IDR_WAVE_QUICKBEEP              4015
#define ID_BUTTON5005                   5005
#define ID_BUTTON5008                   5008
#define ID_BUTTON5009                   5009
#define IDC_SPIN2                       6001
#define IDC_SPIN_UNDOS                  6001
#define IDC_EDIT_UNDOS                  6002
#define IDC_BUTTON6                     6003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4020
#define _APS_NEXT_COMMAND_VALUE         5011
#define _APS_NEXT_CONTROL_VALUE         6004
#define _APS_NEXT_SYMED_VALUE           7001
#endif
#endif
